# Generated by Django 5.1.1 on 2024-09-14 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('system_order_id', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_total', models.FloatField()),
                ('customer_pincode', models.CharField(max_length=10)),
                ('extra_details', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='MiningData',
        ),
    ]
